import Link from "next/link";
import { PageHeader } from "@/components/page-header";
import { prisma } from "@/lib/prisma";
import { CompetencyManager } from "./competency-manager";

export const dynamic = "force-dynamic";

const categoryLabels: Record<string, string> = { frontend: "Front-end", backend: "Back-end", dados: "Dados", database: "Dados", qualidade: "Qualidade", testes: "Qualidade", infraestrutura: "Infraestrutura", devops: "Infraestrutura", gestao: "Gestão e negócios", management: "Gestão e negócios" };
const normalize = (value: string) => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLocaleLowerCase("pt-BR");
const categoryName = (category: string) => categoryLabels[normalize(category)] ?? category;
const levelName = (level: string) => ({ BASICO: "Conhecimento inicial", INTERMEDIARIO: "Aplicação prática", AVANCADO: "Competência consolidada" } as Record<string, string>)[level] ?? level;

export default async function CompetenciasPage() {
  const profile = await prisma.candidateProfile.findFirst({ include: { skills: { orderBy: [{ category: "asc" }, { name: "asc" }] }, projects: { where: { approved: true }, orderBy: { sort_order: "asc" } }, certifications: { orderBy: [{ issued_at: "desc" }, { name: "asc" }] } } });
  const opportunities = await prisma.opportunity.findMany({ where: { active: true }, select: { description: true, requirements: { select: { text: true } } } });
  const marketTexts = opportunities.map((opportunity) => normalize(`${opportunity.description ?? ""} ${opportunity.requirements.map((item) => item.text).join(" ")}`));
  const skills = (profile?.skills ?? []).map((skill) => {
    const name = normalize(skill.name);
    const projects = (profile?.projects ?? []).filter((project) => project.technologies.some((technology) => normalize(technology) === name));
    const certifications = (profile?.certifications ?? []).filter((certification) => normalize(`${certification.name} ${certification.issuer}`).includes(name));
    const demand = opportunities.length ? Math.round(marketTexts.filter((text) => text.includes(name)).length / opportunities.length * 100) : 0;
    return { ...skill, projects, certifications, demand, evidenceCount: projects.length + certifications.length };
  });
  const categories = Array.from(new Set(skills.map((skill) => categoryName(skill.category))));
  const demanded = [...skills].sort((a, b) => b.demand - a.demand).slice(0, 5);
  const gaps = [...skills].filter((skill) => skill.demand >= 10 && skill.evidenceCount === 0).sort((a, b) => b.demand - a.demand).slice(0, 4);

  return <main id="conteudo" className="min-h-screen bg-[#070a10] p-5 text-slate-100 lg:p-8"><div className="mx-auto max-w-7xl">
    <PageHeader eyebrow="Evolução profissional" title="Competências" description="Stacks, certificações e evidências conectadas à demanda das vagas encontradas." />
    <CompetencyManager skills={skills.map((skill) => ({ id: skill.id, name: skill.name, category: skill.category, level: skill.level, yearsExperience: skill.years_experience === null ? null : Number(skill.years_experience), approved: skill.approved }))} certifications={(profile?.certifications ?? []).map((item) => ({ id: item.id, name: item.name, issuer: item.issuer, issuedAt: item.issued_at?.toISOString() ?? null, expiresAt: item.expires_at?.toISOString() ?? null, credentialUrl: item.credential_url, approved: item.approved }))} />
    <section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Competências cadastradas" value={skills.length} /><Metric label="Com evidência prática" value={skills.filter((skill) => skill.evidenceCount > 0).length} color="cyan" /><Metric label="Certificações" value={profile?.certifications.length ?? 0} color="violet" /><Metric label="Vagas analisadas" value={opportunities.length} color="emerald" /></section>
    <div className="mt-6 grid gap-5 xl:grid-cols-[minmax(0,1fr)_340px]"><section className="space-y-5">
      {categories.map((category) => <article key={category} className="rounded-2xl border border-white/10 bg-white/[.025] p-5"><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-semibold">{category}</h2><span className="text-xs text-slate-500">{skills.filter((skill) => categoryName(skill.category) === category).length} competências</span></div><div className="grid gap-3 md:grid-cols-2">{skills.filter((skill) => categoryName(skill.category) === category).map((skill) => <div key={skill.id} className="rounded-xl border border-white/8 bg-[#0b1018] p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold">{skill.name}</h3><p className="mt-1 text-xs text-slate-500">{levelName(skill.level)}{skill.years_experience ? ` · ${Number(skill.years_experience)} ano(s)` : ""}</p></div><span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${skill.approved ? "bg-emerald-400/10 text-emerald-300" : "bg-amber-400/10 text-amber-300"}`}>{skill.approved ? "VALIDADA" : "REVISAR"}</span></div><div className="mt-4 grid grid-cols-2 gap-2 text-xs"><div className="rounded-lg bg-white/[.035] p-2"><span className="text-slate-500">Demanda</span><strong className="mt-1 block text-cyan-300">{skill.demand}% das vagas</strong></div><div className="rounded-lg bg-white/[.035] p-2"><span className="text-slate-500">Evidências</span><strong className="mt-1 block">{skill.evidenceCount}</strong></div></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-slate-800"><div className="h-full rounded-full bg-cyan-400" style={{ width: `${Math.min(skill.demand, 100)}%` }} /></div>{skill.projects.length > 0 && <p className="mt-3 line-clamp-2 text-xs text-slate-400">Projetos: {skill.projects.map((project) => project.name).join(", ")}</p>}</div>)}</div></article>)}
      {skills.length === 0 && <div className="rounded-2xl border border-dashed border-white/10 p-10 text-center"><h2 className="font-semibold">Nenhuma competência cadastrada</h2><p className="mt-2 text-sm text-slate-500">Cadastre suas stacks em Meu perfil para gerar o mapa.</p></div>}
    </section><aside className="space-y-5"><Panel title="Mais procuradas" subtitle="Frequência nas vagas ativas coletadas.">{demanded.map((skill) => <div key={skill.id} className="flex justify-between gap-3 text-sm"><span>{skill.name}</span><strong className="text-cyan-300">{skill.demand}%</strong></div>)}</Panel><Panel title="Próximas evidências" subtitle="Stacks demandadas ainda sem projeto ou certificação.">{gaps.map((skill) => <div key={skill.id} className="rounded-lg bg-black/20 p-3 text-sm"><strong>{skill.name}</strong><span className="mt-1 block text-xs text-slate-500">Associe um projeto ou certificação.</span></div>)}{gaps.length === 0 && <p className="text-sm text-slate-500">Nenhuma lacuna prioritária detectada.</p>}</Panel><Panel title="Certificações" subtitle={`${profile?.certifications.length ?? 0} cadastrada(s)`}>{profile?.certifications.slice(0, 5).map((item) => <div key={item.id} className="rounded-lg bg-black/20 p-3"><p className="text-sm font-medium">{item.name}</p><p className="mt-1 text-xs text-slate-500">{item.issuer}{item.issued_at ? ` · ${item.issued_at.toLocaleDateString("pt-BR")}` : ""}</p></div>)}</Panel><Link href="/career-dna" className="block rounded-xl bg-cyan-300 px-4 py-3 text-center text-sm font-bold text-slate-950 hover:bg-cyan-200">Gerenciar competências e certificações</Link><p className="px-2 text-xs leading-5 text-slate-600">A demanda é estimada pelas descrições disponíveis e não representa garantia de contratação.</p></aside></div>
  </div></main>;
}

function Metric({ label, value, color = "slate" }: { label: string; value: number; color?: "slate" | "cyan" | "violet" | "emerald" }) { const colors = { slate: "border-white/10", cyan: "border-cyan-400/20 bg-cyan-400/[.04]", violet: "border-violet-400/20 bg-violet-400/[.04]", emerald: "border-emerald-400/20 bg-emerald-400/[.04]" }; return <div className={`rounded-xl border p-4 ${colors[color]}`}><p className="text-[10px] tracking-wider text-slate-500 uppercase">{label}</p><p className="mt-2 text-3xl font-semibold">{value}</p></div>; }
function Panel({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-white/10 bg-white/[.025] p-5"><h2 className="font-semibold">{title}</h2><p className="mt-1 text-xs text-slate-500">{subtitle}</p><div className="mt-4 space-y-3">{children}</div></section>; }
