import Link from "next/link";
import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";

export const dynamic = "force-dynamic";

const decisionLabels: Record<string, string> = { APLICAR: "Boa oportunidade", REVISAR: "Revisar com atenção", IGNORAR: "Baixa prioridade" };
const kindLabels: Record<string, string> = { ESSENTIAL: "Essencial", DESIRABLE: "Desejável" };
const stopWords = new Set(["para", "com", "uma", "que", "dos", "das", "por", "como", "ter", "ser", "anos", "experiencia", "conhecimento", "desejavel", "requisito"]);

function normalize(value: string): string { return value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLocaleLowerCase("pt-BR"); }
function words(value: string): string[] { return normalize(value).split(/[^a-z0-9+#.]+/).filter((word) => word.length >= 3 && !stopWords.has(word)); }
function sharedWords(left: string, right: string): number { const rightWords = new Set(words(right)); return new Set(words(left).filter((word) => rightWords.has(word))).size; }
function mentionsSkill(text: string, skill: string): boolean { const normalizedSkill = normalize(skill); if (normalizedSkill.length >= 3) return text.includes(normalizedSkill); return normalize(text).split(/[^a-z0-9+#.]+/).includes(normalizedSkill); }

export default async function OpportunityDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const profile = await prisma.candidateProfile.findFirst({ orderBy: { updated_at: "desc" }, include: { skills: { where: { approved: true } }, projects: { where: { approved: true } }, certifications: { where: { approved: true } }, evidences: { where: { approved: true } } } });
  const profileId = profile?.id ?? "__perfil_ausente__";
  const opportunity = await prisma.opportunity.findUnique({ where: { id }, include: { company: true, requirements: { orderBy: [{ kind: "asc" }, { created_at: "asc" }] }, sources: { orderBy: { discovered_at: "desc" } }, assessments: { where: { profile_id: profileId }, orderBy: { created_at: "desc" }, take: 1 }, applications: { where: { profile_id: profileId }, include: { materials: { select: { id: true, type: true, version: true } }, events: { orderBy: { occurred_at: "desc" }, take: 5 } }, take: 1 } } });
  if (!opportunity) notFound();

  const matrix = opportunity.requirements.map((requirement) => {
    const requirementText = normalize(requirement.text);
    const matchedSkills = (profile?.skills ?? []).filter((skill) => mentionsSkill(requirementText, skill.name));
    const skillNames = new Set(matchedSkills.map((skill) => normalize(skill.name)));
    const projects = (profile?.projects ?? []).filter((project) => project.technologies.some((technology) => skillNames.has(normalize(technology))));
    const certifications = (profile?.certifications ?? []).filter((certification) => matchedSkills.some((skill) => normalize(`${certification.name} ${certification.issuer}`).includes(normalize(skill.name))));
    const evidences = (profile?.evidences ?? []).filter((evidence) => sharedWords(requirement.text, `${evidence.claim} ${evidence.result}`) >= 2);
    const proofCount = projects.length + certifications.length + evidences.length;
    const status = matchedSkills.length > 0 && proofCount > 0 ? "COMPROVADO" : matchedSkills.length > 0 || proofCount > 0 ? "PARCIAL" : "LACUNA";
    return { requirement, matchedSkills, projects, certifications, evidences, status };
  });
  const assessment = opportunity.assessments[0];
  const application = opportunity.applications[0];
  const counts = { proven: matrix.filter((item) => item.status === "COMPROVADO").length, partial: matrix.filter((item) => item.status === "PARCIAL").length, gaps: matrix.filter((item) => item.status === "LACUNA").length };

  return <main id="conteudo" className="min-h-screen bg-[#070a10] p-5 text-slate-100 lg:p-8"><div className="mx-auto max-w-7xl">
    <header className="border-b border-white/10 pb-5"><div className="flex flex-wrap items-start justify-between gap-4"><div className="max-w-4xl"><Link href="/discover" className="text-xs text-cyan-300 hover:text-cyan-200">← Voltar para vagas</Link><h1 className="mt-3 text-3xl font-semibold">{opportunity.title}</h1><p className="mt-1 text-lg text-sky-300">{opportunity.company.name}</p><p className="mt-2 text-sm text-slate-500">{opportunity.location ?? "Localização não informada"}{opportunity.salary_text ? ` · ${opportunity.salary_text}` : ""}</p></div><div className="flex flex-wrap gap-2">{opportunity.sources.map((source) => <a key={source.id} href={source.canonical_url} target="_blank" rel="noreferrer" className="rounded-lg bg-cyan-300 px-4 py-2 text-sm font-bold text-slate-950">Abrir vaga em {source.platform} ↗</a>)}</div></div></header>

    <section className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Metric label="Compatibilidade" value={assessment ? `${assessment.match_score}%` : "—"} color="cyan" /><Metric label="Comprovados" value={counts.proven} color="emerald" /><Metric label="Parciais" value={counts.partial} color="amber" /><Metric label="Lacunas" value={counts.gaps} color="rose" /><Metric label="Candidatura" value={application ? "Existente" : "Não iniciada"} /></section>

    {assessment && <section className="mt-5 rounded-2xl border border-cyan-400/15 bg-cyan-400/[.035] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-semibold tracking-wider text-cyan-300 uppercase">Análise explicável</p><h2 className="mt-1 text-xl font-semibold">{decisionLabels[assessment.decision] ?? assessment.decision}</h2></div><span className="rounded-full bg-cyan-400/10 px-3 py-1 text-sm font-bold text-cyan-300">{assessment.match_score}%</span></div><p className="mt-3 max-w-4xl text-sm leading-6 text-slate-300">{assessment.reason}</p><div className="mt-4 grid gap-3 md:grid-cols-3"><List title="Pontos fortes" items={assessment.strengths} color="emerald" /><List title="Lacunas" items={assessment.gaps} color="amber" /><List title="Riscos" items={assessment.risks} color="rose" /></div><div className="mt-4 rounded-xl bg-black/20 p-4"><p className="text-xs font-semibold text-slate-300">Estratégia sugerida</p><p className="mt-1 text-sm leading-6 text-slate-400">{assessment.strategy}</p></div></section>}

    <section className="mt-5 rounded-2xl border border-white/10 bg-white/[.025] p-5"><div><h2 className="text-xl font-semibold">Matriz de requisitos e evidências</h2><p className="mt-1 text-sm text-slate-500">Somente informações aprovadas no seu perfil são consideradas. “Parcial” significa que a evidência precisa de revisão humana.</p></div><div className="mt-5 space-y-3">{matrix.map((item) => <article key={item.requirement.id} className="grid gap-4 rounded-xl border border-white/8 bg-[#0b1018] p-4 lg:grid-cols-[minmax(0,1fr)_minmax(0,1.25fr)]"><div><div className="flex flex-wrap gap-2"><Badge status={item.status} /><span className="rounded-full bg-white/5 px-2 py-1 text-[10px] text-slate-400">{kindLabels[item.requirement.kind] ?? item.requirement.kind}</span></div><p className="mt-3 text-sm leading-6 text-slate-200">{item.requirement.text}</p></div><div className="space-y-2"><EvidenceLine label="Competências" values={item.matchedSkills.map((skill) => skill.name)} /><EvidenceLine label="Projetos" values={item.projects.map((project) => project.name)} /><EvidenceLine label="Certificações" values={item.certifications.map((certification) => certification.name)} /><EvidenceLine label="Resultados aprovados" values={item.evidences.map((evidence) => `${evidence.claim}: ${evidence.result}`)} />{item.status === "LACUNA" && <p className="rounded-lg bg-rose-400/[.06] p-3 text-xs text-rose-200">Nenhuma evidência aprovada foi encontrada. Isso não significa necessariamente que você não possua a competência.</p>}</div></article>)}{matrix.length === 0 && <p className="rounded-xl border border-dashed border-white/10 p-8 text-center text-sm text-slate-500">A descrição ainda não possui requisitos estruturados suficientes para uma comparação confiável.</p>}</div></section>

    <div className="mt-5 grid gap-5 lg:grid-cols-[minmax(0,1.4fr)_minmax(300px,.6fr)]"><section className="rounded-2xl border border-white/10 bg-white/[.025] p-5"><h2 className="font-semibold">Descrição da oportunidade</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-7 text-slate-400">{opportunity.description ?? "Descrição ainda não disponível."}</p></section><aside className="space-y-4"><section className="rounded-2xl border border-violet-400/15 bg-violet-400/[.035] p-5"><h2 className="font-semibold">Próxima ação</h2>{application ? <><p className="mt-2 text-sm text-slate-400">Esta oportunidade já possui uma candidatura registrada.</p><p className="mt-3 text-xs text-violet-200">{application.materials.length} material(is) · {application.events.length} evento(s) recente(s)</p></> : <p className="mt-2 text-sm leading-6 text-slate-400">Revise a análise e prepare um rascunho interno antes de qualquer ação externa.</p>}<Link href={`/revisao/${opportunity.id}`} className="mt-4 inline-block rounded-lg bg-cyan-300 px-3 py-2 text-sm font-bold text-slate-950">Revisar candidatura</Link></section><Link href="/competencias" className="block rounded-xl border border-white/10 p-4 text-sm text-slate-300 hover:bg-white/[.03]">Atualizar competências e evidências →</Link></aside></div>
  </div></main>;
}

function Metric({ label, value, color = "slate" }: { label: string; value: string | number; color?: "slate" | "cyan" | "emerald" | "amber" | "rose" }) { const colors = { slate: "border-white/10", cyan: "border-cyan-400/20 text-cyan-300", emerald: "border-emerald-400/20 text-emerald-300", amber: "border-amber-400/20 text-amber-300", rose: "border-rose-400/20 text-rose-300" }; return <div className={`rounded-xl border bg-white/[.025] p-4 ${colors[color]}`}><p className="text-[10px] tracking-wider text-slate-500 uppercase">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div>; }
function Badge({ status }: { status: string }) { const style = status === "COMPROVADO" ? "bg-emerald-400/10 text-emerald-300" : status === "PARCIAL" ? "bg-amber-400/10 text-amber-300" : "bg-rose-400/10 text-rose-300"; const label = status === "COMPROVADO" ? "Evidência encontrada" : status === "PARCIAL" ? "Evidência parcial" : "Sem evidência"; return <span className={`rounded-full px-2 py-1 text-[10px] font-bold ${style}`}>{label}</span>; }
function EvidenceLine({ label, values }: { label: string; values: string[] }) { if (!values.length) return null; return <div><p className="text-[10px] font-semibold tracking-wider text-slate-500 uppercase">{label}</p><div className="mt-1 flex flex-wrap gap-1.5">{values.map((value) => <span key={value} className="rounded-md bg-white/5 px-2 py-1 text-xs text-slate-300">{value}</span>)}</div></div>; }
function List({ title, items, color }: { title: string; items: string[]; color: "emerald" | "amber" | "rose" }) { const colors = { emerald: "text-emerald-300", amber: "text-amber-300", rose: "text-rose-300" }; return <div className="rounded-xl bg-black/20 p-3"><p className={`text-xs font-semibold ${colors[color]}`}>{title}</p><ul className="mt-2 space-y-1 text-xs text-slate-400">{items.map((item) => <li key={item}>• {item}</li>)}{items.length === 0 && <li>Nenhum item registrado.</li>}</ul></div>; }
