"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";

import { PdfPreview } from "@/components/pdf-preview";
interface Material { id: string; type: string; version: number; content_text: string | null; content_hash: string; application: { opportunity: { title: string; company: { name: string } } } }
const materialLabels: Record<string, string> = { CV_ATS: "Currículo para ATS", CV_VISUAL: "Currículo visual", EMAIL: "E-mail", COVER_LETTER: "Carta de apresentação", RECRUITER_MESSAGE: "Mensagem ao recrutador", FORM_ANSWERS: "Respostas de formulário" };
export default function MaterialsPage() {
  const [materials, setMaterials] = useState<Material[]>([]); const [selected, setSelected] = useState<Material | null>(null); const [draft, setDraft] = useState(""); const [message, setMessage] = useState<string | null>(null);
  const load = useCallback(async () => { const response = await fetch("/api/materials", { cache: "no-store" }); if (!response.ok) throw new Error("Falha ao carregar materiais."); setMaterials(await response.json() as Material[]); }, []);
  useEffect(() => { const timeout = window.setTimeout(() => void load().catch((error: unknown) => setMessage(error instanceof Error ? error.message : "Falha ao carregar.")), 0); return () => clearTimeout(timeout); }, [load]);
  async function save() { if (!selected) return; const response = await fetch("/api/materials", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ materialId: selected.id, contentText: draft }) }); if (!response.ok) throw new Error("Não foi possível criar a nova versão."); setMessage("Nova versão criada; o material original foi preservado."); setSelected(null); await load(); }
  return <main id="conteudo" className="min-h-screen bg-[#070a10] p-5 text-slate-100 lg:p-8"><header className="mx-auto flex max-w-7xl items-center justify-between border-b border-white/10 pb-5"><div><p className="text-xs tracking-[.2em] text-cyan-300 uppercase">Materiais auditáveis</p><h1 className="mt-1 text-3xl font-semibold">Currículos e mensagens</h1></div><Link href="/pipeline" className="rounded-lg border border-white/10 px-4 py-2 text-sm">← Candidaturas</Link></header>{message && <p className="mx-auto mt-4 max-w-7xl rounded-lg bg-cyan-400/10 p-3 text-sm text-cyan-200">{message}</p>}<div className="mx-auto mt-5 grid max-w-7xl gap-4 lg:grid-cols-[360px_1fr]"><aside className="space-y-2">{materials.map((material) => <button key={material.id} onClick={() => { setSelected(material); setDraft(material.content_text ?? ""); }} className="w-full rounded-xl border border-white/10 bg-white/[.025] p-3 text-left hover:border-cyan-400/30"><div className="flex justify-between text-xs"><strong>{materialLabels[material.type] ?? material.type}</strong><span>versão {material.version}</span></div><p className="mt-1 truncate text-xs text-cyan-300">{material.application.opportunity.title}</p><p className="text-[10px] text-slate-500">{material.application.opportunity.company.name}</p></button>)}{materials.length === 0 && <p className="rounded-xl border border-dashed border-white/10 p-6 text-center text-xs text-slate-500">Nenhum material gerado.</p>}</aside><section className="rounded-2xl border border-white/10 bg-white/[.025] p-4">{!selected && <p className="grid min-h-96 place-items-center text-sm text-slate-600">Selecione um material para visualizar.</p>}{selected && <><div className="mb-3"><h2 className="font-semibold">{materialLabels[selected.type] ?? selected.type} · versão {selected.version}</h2><p className="text-[10px] text-slate-500">Identificador de integridade: {selected.content_hash}</p></div>{selected.content_text !== null ? <><textarea value={draft} onChange={(event) => setDraft(event.target.value)} rows={24} className="w-full rounded-xl border border-white/10 bg-[#0b1018] p-4 font-mono text-xs leading-5 outline-none focus:border-cyan-400/40" /><button onClick={() => void save().catch((error: unknown) => setMessage(error instanceof Error ? error.message : "Falha ao salvar."))} className="mt-3 rounded-lg bg-cyan-400 px-4 py-2 text-sm font-bold text-slate-950">Salvar como nova versão</button></> : <PdfPreview materialId={selected.id} title="Pré-visualização do currículo" />}</>}</section></div></main>;
}
