import Link from "next/link";
import { publicPortfolio } from "@/content/portfolio";

export default function PortfolioPage() {
  return <main id="conteudo" className="min-h-screen overflow-hidden bg-[#070a10] text-slate-100">
    <div aria-hidden className="pointer-events-none absolute inset-x-0 top-0 h-[600px] bg-[radial-gradient(circle_at_20%_20%,rgba(34,211,238,.12),transparent_35%),radial-gradient(circle_at_80%_15%,rgba(167,139,250,.1),transparent_30%)]" />
    <nav className="relative mx-auto flex max-w-7xl items-center justify-between px-5 py-6 lg:px-8"><span className="text-sm font-semibold tracking-wide">Job Hunter OS</span><div className="flex items-center gap-2"><a href="#projeto" className="hidden px-3 py-2 text-xs text-slate-400 hover:text-white sm:block">O projeto</a><a href="#competencias" className="hidden px-3 py-2 text-xs text-slate-400 hover:text-white sm:block">Competências</a><Link href="/login" className="rounded-lg border border-white/10 px-3 py-2 text-xs text-slate-300 hover:bg-white/5">Área privada</Link></div></nav>

    <section className="relative mx-auto grid min-h-[620px] max-w-7xl items-center gap-12 px-5 py-16 lg:grid-cols-[1.1fr_.9fr] lg:px-8"><div><p className="text-xs font-bold tracking-[.24em] text-cyan-300 uppercase">Desenvolvimento Full Stack · Produto · IA</p><h1 className="mt-5 max-w-4xl text-5xl leading-[1.05] font-semibold tracking-tight md:text-7xl">Tecnologia com visão de <span className="text-cyan-300">negócio e execução.</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-400">{publicPortfolio.summary}</p><div className="mt-8 flex flex-wrap gap-3">{publicPortfolio.links.map((link) => <a key={link.href} href={link.href} target="_blank" rel="noreferrer" className="rounded-xl bg-cyan-300 px-5 py-3 text-sm font-bold text-slate-950 transition hover:bg-cyan-200">{link.label} ↗</a>)}<a href="#projeto" className="rounded-xl border border-white/10 px-5 py-3 text-sm font-semibold hover:bg-white/5">Conhecer o projeto</a></div></div><div className="relative rounded-3xl border border-white/10 bg-white/[.035] p-5 shadow-2xl shadow-cyan-950/20"><div className="flex items-center justify-between border-b border-white/10 pb-4"><div><p className="text-[10px] tracking-wider text-slate-500 uppercase">Sistema operacional de carreira</p><h2 className="mt-1 font-semibold">Visão geral demonstrativa</h2></div><span className="rounded-full bg-emerald-400/10 px-2 py-1 text-[10px] font-bold text-emerald-300">MODO SEGURO</span></div><div className="mt-4 grid grid-cols-3 gap-2">{[["Vagas", "24"], ["Alta aderência", "7"], ["Para revisar", "3"]].map(([label, value]) => <div key={label} className="rounded-xl bg-black/20 p-3"><p className="text-[9px] text-slate-500 uppercase">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div>)}</div><div className="mt-4 space-y-2">{[["Full Stack TypeScript", "91%"], ["Front-end React", "86%"], ["Node.js Júnior", "82%"]].map(([title, score]) => <div key={title} className="flex items-center justify-between rounded-xl border border-white/8 bg-black/20 p-3"><div><p className="text-sm font-medium">{title}</p><p className="text-[10px] text-slate-500">Empresa demonstrativa</p></div><strong className="text-cyan-300">{score}</strong></div>)}</div><p className="mt-4 text-center text-[10px] text-slate-600">Dados fictícios para demonstração pública</p></div></section>

    <section className="border-y border-white/8 bg-white/[.018]"><div className="mx-auto grid max-w-7xl gap-5 px-5 py-14 md:grid-cols-3 lg:px-8">{publicPortfolio.strengths.map((strength, index) => <article key={strength.title} className="rounded-2xl border border-white/8 bg-black/10 p-5"><span className="text-xs font-bold text-cyan-300">0{index + 1}</span><h2 className="mt-3 text-lg font-semibold">{strength.title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{strength.description}</p></article>)}</div></section>

    <section id="projeto" className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="max-w-3xl"><p className="text-xs font-bold tracking-[.2em] text-violet-300 uppercase">Estudo de caso</p><h2 className="mt-4 text-4xl font-semibold">Um produto real para um problema real</h2><p className="mt-5 text-lg leading-8 text-slate-400">O Job Hunter OS organiza descoberta, análise, preparação e acompanhamento de oportunidades. A automação foi desenhada para ampliar produtividade sem inventar fatos, armazenar cookies de plataformas ou remover decisões humanas sensíveis.</p></div><div className="mt-12 grid gap-4 lg:grid-cols-4">{publicPortfolio.architecture.map((item, index) => <article key={item.step} className="relative rounded-2xl border border-white/10 bg-white/[.025] p-5"><span className="text-4xl font-semibold text-white/5">{index + 1}</span><h3 className="mt-5 font-semibold text-cyan-200">{item.step}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{item.description}</p></article>)}</div><div className="mt-8 grid gap-3 md:grid-cols-2">{publicPortfolio.highlights.map((highlight) => <p key={highlight} className="flex gap-3 rounded-xl border border-white/8 bg-black/10 p-4 text-sm text-slate-300"><span className="text-emerald-300">✓</span>{highlight}</p>)}</div></section>

    <section id="competencias" className="border-y border-white/8 bg-[#0a0f18]"><div className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><p className="text-xs font-bold tracking-[.2em] text-cyan-300 uppercase">Competências técnicas</p><h2 className="mt-4 text-4xl font-semibold">Stack aplicada no produto</h2><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{publicPortfolio.stack.map((group) => <article key={group.category} className="rounded-2xl border border-white/10 bg-white/[.025] p-5"><h3 className="font-semibold">{group.category}</h3><div className="mt-4 flex flex-wrap gap-2">{group.items.map((item) => <span key={item} className="rounded-lg bg-white/5 px-2.5 py-1.5 text-xs text-slate-300">{item}</span>)}</div></article>)}</div></div></section>

    <section className="mx-auto max-w-4xl px-5 py-24 text-center"><p className="text-xs font-bold tracking-[.2em] text-violet-300 uppercase">Contato profissional</p><h2 className="mt-4 text-4xl font-semibold">Vamos construir algo útil.</h2><p className="mx-auto mt-4 max-w-2xl text-slate-400">Conheça minha trajetória, experiência em projetos e desenvolvimento Full Stack pelos canais profissionais.</p><div className="mt-8 flex justify-center gap-3">{publicPortfolio.links.map((link) => <a key={link.href} href={link.href} target="_blank" rel="noreferrer" className="rounded-xl bg-cyan-300 px-5 py-3 text-sm font-bold text-slate-950">{link.label} ↗</a>)}</div></section>
    <footer className="border-t border-white/8 px-5 py-8 text-center text-xs text-slate-600">© {new Date().getFullYear()} {publicPortfolio.name} · Construído com TypeScript e visão de produto.</footer>
  </main>;
}
