import Link from "next/link";
import { PageHeader } from "@/components/page-header";
import { prisma } from "@/lib/prisma";

export const dynamic = "force-dynamic";
const decisionLabels: Record<string, string> = { APLICAR: "RECOMENDADA", REVISAR: "REVISAR", IGNORAR: "BAIXA PRIORIDADE" };

export default async function DiscoverPage() {
  const profile = await prisma.candidateProfile.findFirst({ orderBy: { updated_at: "desc" }, select: { id: true } });
  const opportunities = await prisma.opportunity.findMany({ where: { active: true }, orderBy: { last_seen_at: "desc" }, take: 100, include: { company: true, sources: true, requirements: { select: { id: true } }, assessments: profile ? { where: { profile_id: profile.id }, orderBy: { created_at: "desc" }, take: 1 } : false, applications: profile ? { where: { profile_id: profile.id }, take: 1 } : false } });
  return <main id="conteudo" className="min-h-screen bg-[#070a10] p-5 text-slate-100 lg:p-8"><div className="mx-auto max-w-7xl"><PageHeader eyebrow="Inteligência de oportunidades" title="Vagas" description="Oportunidades organizadas, sem duplicidade e explicadas antes de qualquer ação." /><section className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{opportunities.map((opportunity) => { const assessment = opportunity.assessments[0]; return <article key={opportunity.id} className="flex flex-col rounded-2xl border border-white/10 bg-white/[.025] p-4"><div className="flex justify-between"><span className="text-xs text-slate-500">{opportunity.sources.map((source) => source.platform).join(" · ")}</span><strong className="text-cyan-300">{assessment?.match_score ?? "—"}%</strong></div><h2 className="mt-2 font-semibold">{opportunity.title}</h2><p className="text-sm text-sky-300">{opportunity.company.name}</p><p className="mt-2 line-clamp-3 flex-1 text-xs leading-5 text-slate-500">{opportunity.description ?? "Descrição ainda não enriquecida."}</p><p className="mt-3 text-[10px] text-slate-600">{opportunity.requirements.length} requisito(s) estruturado(s)</p><div className="mt-4 flex flex-wrap items-center justify-between gap-2"><span className={`text-[10px] font-bold ${opportunity.applications.length ? "text-emerald-300" : "text-slate-500"}`}>{opportunity.applications.length ? "CANDIDATURA EXISTENTE" : assessment ? decisionLabels[assessment.decision] ?? assessment.decision : "NÃO AVALIADA"}</span><div className="flex gap-2"><Link href={`/discover/${opportunity.id}`} className="rounded-lg border border-cyan-400/20 px-3 py-2 text-xs font-semibold text-cyan-300">Analisar detalhes</Link>{opportunity.sources[0] && <a href={opportunity.sources[0].canonical_url} target="_blank" rel="noreferrer" className="rounded-lg bg-cyan-400 px-3 py-2 text-xs font-bold text-slate-950">Abrir vaga</a>}</div></div></article>; })}{opportunities.length === 0 && <p className="rounded-2xl border border-dashed border-white/10 p-10 text-center text-sm text-slate-500 md:col-span-2 xl:col-span-3">Nenhuma vaga ativa encontrada.</p>}</section></div></main>;
}
