import Link from "next/link";
import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { ReviewClient } from "./review-client";

export const dynamic = "force-dynamic";
export default async function ReviewPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const profile = await prisma.candidateProfile.findFirst({ orderBy: { updated_at: "desc" }, select: { id: true } }); const profileId = profile?.id ?? "__perfil_ausente__";
  const opportunity = await prisma.opportunity.findUnique({ where: { id }, include: { company: true, sources: { orderBy: { discovered_at: "desc" } }, assessments: { where: { profile_id: profileId }, orderBy: { created_at: "desc" }, take: 1 }, applications: { where: { profile_id: profileId }, take: 1, include: { materials: { orderBy: [{ type: "asc" }, { version: "desc" }] } } } } });
  if (!opportunity) notFound(); const application = opportunity.applications[0] ?? null; const seen = new Set<string>(); const latestMaterials = (application?.materials ?? []).filter((material) => { if (seen.has(material.type)) return false; seen.add(material.type); return true; }); const assessment = opportunity.assessments[0];
  return <main id="conteudo" className="min-h-screen bg-[#070a10] p-5 text-slate-100 lg:p-8"><div className="mx-auto max-w-7xl"><header className="border-b border-white/10 pb-5"><Link href={`/discover/${id}`} className="text-xs text-cyan-300">← Voltar para análise</Link><h1 className="mt-3 text-3xl font-semibold">Revisar candidatura</h1><p className="mt-1 text-lg text-sky-300">{opportunity.title} · {opportunity.company.name}</p></header><section className="mt-5 grid gap-4 lg:grid-cols-[minmax(0,1fr)_320px]"><div className="rounded-2xl border border-white/10 bg-white/[.025] p-5"><h2 className="font-semibold">Resumo da decisão</h2><p className="mt-2 text-sm leading-6 text-slate-400">{assessment?.reason ?? "Esta oportunidade ainda não possui análise suficiente."}</p>{assessment && <div className="mt-4 flex items-center gap-3"><strong className="text-2xl text-cyan-300">{assessment.match_score}%</strong><span className="text-xs text-slate-500">{assessment.decision}</span></div>}</div><aside className="rounded-2xl border border-emerald-400/15 bg-emerald-400/[.035] p-5"><h2 className="font-semibold">Canal da candidatura</h2><div className="mt-3 space-y-2">{opportunity.sources.map((source) => <a key={source.id} href={source.canonical_url} target="_blank" rel="noreferrer" className="block rounded-lg bg-black/20 p-3 text-sm text-emerald-200">Abrir {source.platform} ↗</a>)}</div></aside></section><div className="mt-5"><ReviewClient opportunityId={id} applicationId={application?.id ?? null} status={application?.status ?? null} materials={latestMaterials.map((material) => ({ id: material.id, type: material.type, version: material.version, contentText: material.content_text }))} /></div></div></main>;
}
