"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";

interface Material { id: string; type: string; version: number; contentText: string | null }
const labels: Record<string, string> = { CV_ATS: "Currículo para ATS", CV_VISUAL: "Currículo visual", EMAIL: "E-mail personalizado", COVER_LETTER: "Carta de apresentação", RECRUITER_MESSAGE: "Mensagem ao recrutador", FORM_ANSWERS: "Respostas de formulário" };

export function ReviewClient({ opportunityId, applicationId, status, materials }: { opportunityId: string; applicationId: string | null; status: string | null; materials: Material[] }) {
  const router = useRouter(); const [selectedId, setSelectedId] = useState(materials[0]?.id ?? ""); const selected = materials.find((item) => item.id === selectedId) ?? null; const [drafts, setDrafts] = useState<Record<string, string>>(() => Object.fromEntries(materials.filter((item) => item.contentText !== null).map((item) => [item.id, item.contentText ?? ""]))); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function createDraft() { setBusy(true); setMessage(""); const response = await fetch("/api/applications/review", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ opportunityId }) }); if (!response.ok) { const data = await response.json() as { error?: string }; setMessage(data.error ?? "Falha ao criar rascunho."); setBusy(false); return; } router.refresh(); }
  async function saveMaterial() { if (!selected || selected.contentText === null) return; setBusy(true); setMessage(""); const response = await fetch("/api/materials", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ materialId: selected.id, contentText: drafts[selected.id] }) }); if (!response.ok) { setMessage("Não foi possível salvar a nova versão."); setBusy(false); return; } setMessage("Nova versão salva. A versão anterior foi preservada."); setBusy(false); router.refresh(); }
  async function markReady() { if (!applicationId) return; setBusy(true); setMessage(""); const response = await fetch("/api/applications/review", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ applicationId }) }); if (!response.ok) { const data = await response.json() as { error?: string }; setMessage(data.error ?? "Falha ao concluir revisão."); setBusy(false); return; } setMessage("Revisão concluída. Nenhum envio foi realizado."); setBusy(false); router.refresh(); }
  if (!applicationId) return <section className="rounded-2xl border border-cyan-400/20 bg-cyan-400/[.04] p-6"><h2 className="text-lg font-semibold">Preparar candidatura</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">Crie um rascunho interno para reunir currículo e mensagens. Isso não chama IA, não abre plataformas e não envia e-mail.</p><button disabled={busy} onClick={() => void createDraft()} className="mt-4 rounded-lg bg-cyan-300 px-4 py-2 text-sm font-bold text-slate-950 disabled:opacity-50">{busy ? "Criando..." : "Criar rascunho seguro"}</button>{message && <p className="mt-3 text-sm text-rose-300">{message}</p>}</section>;
  return <section className="rounded-2xl border border-white/10 bg-white/[.025] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">Materiais da candidatura</h2><p className="mt-1 text-xs text-slate-500">Status: {status === "DRAFT" ? "Em preparação" : status === "MANUAL_ACTION" ? "Aguardando ação manual" : status}</p></div><span className="rounded-full bg-emerald-400/10 px-3 py-1 text-xs font-bold text-emerald-300">NENHUM ENVIO AUTOMÁTICO</span></div>{message && <p className="mt-4 rounded-lg bg-cyan-400/10 p-3 text-sm text-cyan-200">{message}</p>}<div className="mt-5 grid gap-4 lg:grid-cols-[280px_minmax(0,1fr)]"><aside className="space-y-2">{materials.map((material) => <button key={material.id} onClick={() => setSelectedId(material.id)} className={`w-full rounded-lg border p-3 text-left text-sm ${selectedId === material.id ? "border-cyan-400/30 bg-cyan-400/[.06]" : "border-white/10 bg-black/20"}`}><strong>{labels[material.type] ?? material.type}</strong><span className="mt-1 block text-xs text-slate-500">Versão {material.version}</span></button>)}{materials.length === 0 && <p className="rounded-lg border border-dashed border-white/10 p-5 text-center text-xs text-slate-500">Os materiais aparecerão quando forem preparados no modo seguro.</p>}</aside><div>{selected?.contentText !== null && selected ? <><textarea value={drafts[selected.id] ?? ""} onChange={(event) => setDrafts({ ...drafts, [selected.id]: event.target.value })} rows={22} className="w-full rounded-xl border border-white/10 bg-slate-950 p-4 text-sm leading-6 outline-none focus:border-cyan-400/40" /><button disabled={busy || !(drafts[selected.id]?.trim())} onClick={() => void saveMaterial()} className="mt-3 rounded-lg border border-cyan-400/20 px-4 py-2 text-sm font-semibold text-cyan-300 disabled:opacity-40">Salvar como nova versão</button></> : selected ? <iframe title={labels[selected.type] ?? selected.type} src={`/api/materials/${selected.id}`} className="h-[70vh] w-full rounded-xl bg-white" /> : <p className="grid min-h-72 place-items-center text-sm text-slate-600">Selecione um material para revisar.</p>}</div></div>{status === "DRAFT" && <div className="mt-5 border-t border-white/10 pt-5"><button disabled={busy} onClick={() => void markReady()} className="rounded-lg bg-violet-300 px-4 py-2 text-sm font-bold text-slate-950 disabled:opacity-50">Concluir revisão e enviar para Pendências</button><p className="mt-2 text-xs text-slate-500">Esta ação muda apenas o status interno. A candidatura continuará dependendo de ação humana.</p></div>}</section>;
}

