"use client";
import Link from "next/link";
import { useEffect, useState } from "react";

interface Action { id: string; status: string; opportunity: { title: string; company: { name: string }; sources: Array<{ id: string; platform: string; canonical_url: string }>; assessments: Array<{ match_score: number; strategy: string; gaps: string[] }> }; materials: Array<{ id: string }>; follow_ups: Array<{ id: string; body: string }> }
const statuses: Record<string, string> = { DRAFT: "Em preparação", MANUAL_ACTION: "Aguardando sua ação" };

export default function ActionCenterPage() {
  const [actions, setActions] = useState<Action[]>([]); const [error, setError] = useState<string | null>(null);
  useEffect(() => { const timeout = setTimeout(() => void fetch("/api/action-center", { cache: "no-store" }).then(async (response) => { if (!response.ok) throw new Error("Falha ao carregar as pendências."); setActions(await response.json() as Action[]); }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "Falha ao carregar.")), 0); return () => clearTimeout(timeout); }, []);
  async function decideFollowUp(id: string, approved: boolean) { const response = await fetch("/api/follow-ups", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, approved }) }); if (!response.ok) throw new Error("Falha ao decidir o acompanhamento."); setActions((current) => current.map((action) => ({ ...action, follow_ups: action.follow_ups.filter((item) => item.id !== id) }))); }
  return <main id="conteudo" className="min-h-screen bg-[#070a10] p-5 text-slate-100 lg:p-8"><header className="mx-auto flex max-w-7xl items-center justify-between border-b border-white/10 pb-5"><div><p className="text-xs tracking-[.2em] text-orange-300 uppercase">Decisões humanas prioritárias</p><h1 className="mt-1 text-3xl font-semibold">Pendências</h1></div><Link href="/pipeline" className="rounded-lg border border-white/10 px-4 py-2 text-sm">← Candidaturas</Link></header>{error && <p className="mx-auto mt-4 max-w-7xl text-rose-300">{error}</p>}<section className="mx-auto mt-5 grid max-w-7xl gap-3 md:grid-cols-2 xl:grid-cols-3">{actions.map((action) => { const assessment = action.opportunity.assessments[0]; return <article key={action.id} className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><div className="flex justify-between"><span className="rounded-full bg-orange-400/10 px-2 py-1 text-[10px] font-bold text-orange-300">{statuses[action.status] ?? action.status}</span><strong className="text-cyan-300">{assessment?.match_score ?? "—"}%</strong></div><h2 className="mt-3 font-semibold">{action.opportunity.title}</h2><p className="text-sm text-slate-400">{action.opportunity.company.name}</p><p className="mt-3 line-clamp-3 text-xs text-slate-500">{assessment?.strategy ?? "Revisão manual necessária."}</p>{assessment?.gaps[0] && <p className="mt-2 text-xs text-amber-300">Lacuna: {assessment.gaps[0]}</p>}{action.follow_ups.map((followUp) => <div key={followUp.id} className="mt-3 rounded-lg border border-violet-400/20 bg-violet-400/[.06] p-3"><p className="text-xs font-semibold text-violet-300">Acompanhamento aguardando aprovação</p><p className="mt-1 line-clamp-2 text-[11px] text-slate-400">{followUp.body}</p><div className="mt-2 flex gap-2"><button onClick={() => void decideFollowUp(followUp.id, true).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "Falha."))} className="rounded bg-emerald-400 px-2 py-1 text-[10px] font-bold text-slate-950">Aprovar</button><button onClick={() => void decideFollowUp(followUp.id, false).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "Falha."))} className="rounded border border-rose-400/20 px-2 py-1 text-[10px] text-rose-300">Cancelar</button></div></div>)}<div className="mt-4 flex flex-wrap gap-2">{action.opportunity.sources.map((source) => <a key={source.id} href={source.canonical_url} target="_blank" rel="noreferrer" className="rounded-lg bg-cyan-400 px-3 py-2 text-xs font-bold text-slate-950">Abrir vaga</a>)}<Link href="/materials" className="rounded-lg border border-white/10 px-3 py-2 text-xs">Materiais ({action.materials.length})</Link></div></article>; })}{actions.length === 0 && <p className="rounded-2xl border border-dashed border-white/10 p-10 text-center text-sm text-slate-500 md:col-span-2 xl:col-span-3">Nenhuma ação manual pendente.</p>}</section></main>;
}

