import Link from "next/link";
import { PageHeader } from "@/components/page-header";
import { calculateFunnel } from "@/lib/analytics";
import { prisma } from "@/lib/prisma";

export const dynamic = "force-dynamic";

const applicationStatus: Record<string, string> = { DRAFT: "Em preparação", MANUAL_ACTION: "Aguardando sua ação", SUBMITTED: "Candidatura realizada", TEST: "Teste técnico", INTERVIEW: "Entrevista", REJECTED: "Não avançou", WITHDRAWN: "Retirada", OFFER: "Proposta recebida" };
const connectorStatus: Record<string, string> = { RUNNING: "Executando", SUCCESS: "Concluído", PARTIAL: "Concluído parcialmente", FAILED: "Falhou" };

export default async function TodayPage() {
  const [profile, discovered, applications, actions, bestOpportunities, interviews, connectorRuns, pendingQueue] = await Promise.all([
    prisma.candidateProfile.findFirst({ select: { nome: true } }),
    prisma.opportunity.count({ where: { active: true } }),
    prisma.application.findMany({ include: { opportunity: { include: { sources: { select: { platform: true } }, requirements: { select: { text: true } } } } } }),
    prisma.application.findMany({ where: { status: { in: ["DRAFT", "MANUAL_ACTION"] } }, orderBy: { updated_at: "desc" }, take: 5, include: { opportunity: { include: { company: true } } } }),
    prisma.opportunityAssessment.findMany({ where: { description_sufficient: true }, orderBy: [{ match_score: "desc" }, { created_at: "desc" }], take: 5, include: { opportunity: { include: { company: true, sources: { orderBy: { discovered_at: "desc" }, take: 1 } } } } }),
    prisma.interview.findMany({ where: { scheduled_at: { gte: new Date() } }, orderBy: { scheduled_at: "asc" }, take: 3, include: { application: { include: { opportunity: { include: { company: true } } } } } }),
    prisma.connectorRun.findMany({ orderBy: { started_at: "desc" }, distinct: ["connector"], take: 5 }),
    prisma.queueItem.count({ where: { status: { in: ["PENDING", "PROCESSING", "FAILED"] } } }),
  ]);
  const funnel = calculateFunnel(applications, discovered);
  const firstName = profile?.nome.split(" ")[0] ?? "Candidato";

  return <main id="conteudo" className="min-h-screen bg-[#070a10] p-5 text-slate-100 lg:p-8"><div className="mx-auto max-w-7xl">
    <PageHeader eyebrow="Central de comando" title={`Olá, ${firstName}`} description="Estas são as oportunidades e decisões que mais merecem sua atenção agora." />

    <section className="mt-6 flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-emerald-400/20 bg-emerald-400/[.05] p-4"><div><div className="flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-full bg-emerald-400" /><h2 className="font-semibold">Robô em modo seguro</h2></div><p className="mt-1 text-sm text-slate-400">Buscando oportunidades. Nenhum e-mail ou candidatura será enviado automaticamente.</p></div><span className="rounded-full border border-emerald-400/20 bg-emerald-400/10 px-3 py-1.5 text-xs font-bold text-emerald-300">SOMENTE OBSERVAR</span></section>

    <section className="mt-5 grid grid-cols-2 gap-3 lg:grid-cols-6">{[["Vagas encontradas", funnel.discovered], ["Candidaturas", funnel.applications], ["Respostas", funnel.responses], ["Testes", funnel.tests], ["Entrevistas", funnel.interviews], ["Propostas", funnel.offers]].map(([label, value]) => <div key={label} className="rounded-xl border border-white/10 bg-white/[.025] p-4"><p className="text-[10px] text-slate-500 uppercase">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div>)}</section>

    <div className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1.4fr)_minmax(320px,.6fr)]"><section className="rounded-2xl border border-orange-400/15 bg-orange-400/[.035] p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="font-semibold">Prioridades de hoje</h2><p className="mt-1 text-xs text-slate-500">Candidaturas que dependem da sua decisão.</p></div><Link href="/action-center" className="text-xs font-semibold text-orange-300 hover:text-orange-200">Ver todas →</Link></div><div className="mt-4 space-y-2">{actions.map((action) => <Link href="/action-center" key={action.id} className="flex items-center justify-between gap-4 rounded-xl bg-black/20 p-3 transition hover:bg-black/30"><div className="min-w-0"><strong className="block truncate text-sm">{action.opportunity.title}</strong><p className="truncate text-xs text-slate-500">{action.opportunity.company.name}</p></div><span className="shrink-0 rounded-full bg-orange-400/10 px-2 py-1 text-[10px] text-orange-300">{applicationStatus[action.status] ?? action.status}</span></Link>)}{actions.length === 0 && <Empty text="Nenhuma decisão pendente. Sua fila está em dia." />}</div></section>

      <section className="rounded-2xl border border-white/10 bg-white/[.025] p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Atividade do sistema</h2><p className="mt-1 text-xs text-slate-500">Últimas fontes executadas.</p></div><span className="text-xs text-slate-500">Fila: {pendingQueue}</span></div><div className="mt-4 space-y-3">{connectorRuns.map((run) => <div key={run.id} className="border-l border-cyan-400/30 pl-3"><div className="flex justify-between gap-3 text-xs"><strong>{run.connector}</strong><span className={run.status === "SUCCESS" ? "text-emerald-300" : run.status === "FAILED" ? "text-red-300" : "text-amber-300"}>{connectorStatus[run.status] ?? run.status}</span></div><p className="mt-1 text-[11px] text-slate-500">{run.persisted} salvas · {run.error_count} erros · {run.started_at.toLocaleString("pt-BR")}</p></div>)}{connectorRuns.length === 0 && <Empty text="Nenhuma execução registrada." />}</div></section></div>

    <section className="mt-5 rounded-2xl border border-cyan-400/15 bg-cyan-400/[.025] p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="font-semibold">Melhores oportunidades</h2><p className="mt-1 text-xs text-slate-500">Compatibilidade calculada usando apenas fatos aprovados do seu perfil.</p></div><Link href="/discover" className="text-xs font-semibold text-cyan-300 hover:text-cyan-200">Explorar vagas →</Link></div><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-5">{bestOpportunities.map((assessment) => <article key={assessment.id} className="rounded-xl border border-white/8 bg-[#0b1018] p-4"><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${assessment.match_score >= 80 ? "bg-emerald-400/10 text-emerald-300" : "bg-amber-400/10 text-amber-300"}`}>{assessment.match_score}% compatível</span><h3 className="mt-3 line-clamp-2 text-sm font-semibold">{assessment.opportunity.title}</h3><p className="mt-1 truncate text-xs text-cyan-300">{assessment.opportunity.company.name}</p><p className="mt-3 line-clamp-3 text-xs leading-5 text-slate-500">{assessment.reason}</p>{assessment.opportunity.sources[0] && <a href={assessment.opportunity.sources[0].canonical_url} target="_blank" rel="noreferrer" className="mt-3 inline-block text-xs font-semibold text-slate-300 hover:text-white">Ver vaga ↗</a>}</article>)}{bestOpportunities.length === 0 && <Empty text="As melhores oportunidades aparecerão após a análise segura." />}</div></section>

    <div className="mt-5 grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border border-emerald-400/15 bg-emerald-400/[.035] p-5"><div className="flex justify-between"><h2 className="font-semibold">Próximas entrevistas</h2><Link href="/interviews" className="text-xs text-emerald-300">Abrir preparação →</Link></div><div className="mt-3 space-y-2">{interviews.map((interview) => <p key={interview.id} className="rounded-xl bg-black/20 p-3 text-sm"><strong>{interview.application.opportunity.title}</strong><span className="block text-xs text-slate-500">{interview.application.opportunity.company.name} · {interview.scheduled_at?.toLocaleString("pt-BR")}</span></p>)}{interviews.length === 0 && <Empty text="Nenhuma entrevista agendada." />}</div></section><section className="rounded-2xl border border-violet-400/15 bg-violet-400/[.035] p-5"><h2 className="font-semibold">Desenvolvimento profissional</h2><p className="mt-2 text-sm leading-6 text-slate-400">Veja quais competências aparecem nas vagas, quais possuem evidências e onde concentrar seus próximos estudos.</p><Link href="/competencias" className="mt-4 inline-block rounded-lg bg-violet-400/15 px-3 py-2 text-sm font-semibold text-violet-200 hover:bg-violet-400/20">Abrir painel de competências →</Link></section></div>
  </div></main>;
}

function Empty({ text }: { text: string }) { return <p className="rounded-xl border border-dashed border-white/10 p-5 text-center text-xs text-slate-500">{text}</p>; }
