"use client";

import { type FormEvent, useCallback, useEffect, useState } from "react";
import { PageHeader } from "@/components/page-header";

interface Target { id: string; name: string; careers_url: string; platform: string; identifier: string | null; enabled: boolean; priority: number; notes: string | null }
const automated = new Set(["GREENHOUSE", "LEVER", "ASHBY", "WORKABLE", "SMARTRECRUITERS"]);

export default function SourcesPage() {
  const [targets, setTargets] = useState<Target[]>([]); const [message, setMessage] = useState<string | null>(null);
  const load = useCallback(async () => { const response = await fetch("/api/company-targets", { cache: "no-store" }); if (!response.ok) throw new Error("Falha ao carregar fontes."); setTargets(await response.json() as Target[]); }, []);
  useEffect(() => { const timeout = window.setTimeout(() => void load().catch((error: unknown) => setMessage(error instanceof Error ? error.message : "Falha.")), 0); return () => window.clearTimeout(timeout); }, [load]);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const response = await fetch("/api/company-targets", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: data.get("name"), careersUrl: data.get("careersUrl"), platform: data.get("platform"), identifier: data.get("identifier") || null, priority: Number(data.get("priority") || 0), enabled: false }) }); if (!response.ok) throw new Error("Revise os dados da página de carreira."); event.currentTarget.reset(); await load(); }
  async function toggle(target: Target) { const response = await fetch("/api/company-targets", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: target.id, enabled: !target.enabled }) }); if (!response.ok) throw new Error("Não foi possível atualizar a fonte."); await load(); }
  return <main id="conteudo" className="min-h-screen bg-[#070a10] p-5 text-slate-100 lg:p-8"><div className="mx-auto max-w-7xl"><PageHeader eyebrow="Origem das oportunidades" title="Fontes e empresas-alvo" description="Cadastre páginas oficiais. Fontes públicas podem rodar autonomamente; Gupy, Indeed e sites genéricos permanecem assistidos." />
    {message && <p role="alert" className="mt-4 rounded-lg bg-rose-400/10 p-3 text-sm text-rose-300">{message}</p>}
    <form onSubmit={(event) => void create(event).catch((error: unknown) => setMessage(error instanceof Error ? error.message : "Falha."))} className="mt-5 grid gap-3 rounded-2xl border border-white/10 bg-white/[.025] p-4 md:grid-cols-2 xl:grid-cols-6"><label className="text-xs text-slate-400 xl:col-span-2">Empresa<input required name="name" className="mt-1 w-full rounded-lg border border-white/10 bg-black/20 p-2 text-white" /></label><label className="text-xs text-slate-400 xl:col-span-2">Página oficial<input required type="url" name="careersUrl" className="mt-1 w-full rounded-lg border border-white/10 bg-black/20 p-2 text-white" /></label><label className="text-xs text-slate-400">Plataforma<select name="platform" className="mt-1 w-full rounded-lg border border-white/10 bg-[#0d121b] p-2 text-white">{["GREENHOUSE", "LEVER", "ASHBY", "WORKABLE", "SMARTRECRUITERS", "GUPY", "INDEED", "COMPANY_SITE"].map((value) => <option key={value}>{value}</option>)}</select></label><label className="text-xs text-slate-400">Prioridade<input name="priority" type="number" min="0" max="100" defaultValue="50" className="mt-1 w-full rounded-lg border border-white/10 bg-black/20 p-2 text-white" /></label><label className="text-xs text-slate-400 xl:col-span-2">Identificador do ATS<input name="identifier" placeholder="subdomínio ou board token" className="mt-1 w-full rounded-lg border border-white/10 bg-black/20 p-2 text-white" /></label><button className="self-end rounded-lg bg-cyan-400 px-4 py-2 text-sm font-bold text-slate-950">Adicionar desabilitada</button></form>
    <section className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{targets.map((target) => <article key={target.id} className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold">{target.name}</h2><p className="text-xs text-cyan-300">{target.platform} · prioridade {target.priority}</p></div><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${automated.has(target.platform) ? "bg-emerald-400/10 text-emerald-300" : "bg-amber-400/10 text-amber-300"}`}>{automated.has(target.platform) ? "AUTÔNOMA" : "ASSISTIDA"}</span></div><a href={target.careers_url} target="_blank" rel="noreferrer" className="mt-3 block truncate text-xs text-slate-500 underline">{target.careers_url}</a><div className="mt-4 flex items-center justify-between"><span className="text-xs text-slate-500">{target.enabled ? "Habilitada" : "Desabilitada"}</span><button onClick={() => void toggle(target).catch((error: unknown) => setMessage(error instanceof Error ? error.message : "Falha."))} disabled={!automated.has(target.platform) && !target.enabled} className="rounded-lg border border-white/10 px-3 py-2 text-xs disabled:cursor-not-allowed disabled:opacity-40">{target.enabled ? "Desabilitar" : "Habilitar"}</button></div></article>)}{!targets.length && <p className="rounded-2xl border border-dashed border-white/10 p-10 text-center text-sm text-slate-500 md:col-span-2 xl:col-span-3">Nenhuma empresa-alvo cadastrada. Não inventaremos prioridades sem sua revisão.</p>}</section>
  </div></main>;
}
